import Foundation
@testable import Orbit

/// The committed file fixtures (OrbitTests/Fixtures/Files, generated by
/// make-fixtures.sh), and tool contexts that can only reach them.
enum FileFixtures {
    /// Canonical path of the fixture folder.
    static let root: String = {
        let tests = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
        return FilePath.canonical(tests.appendingPathComponent("Fixtures/Files").path)
    }()

    static func path(_ relativePath: String) -> String {
        root + "/" + relativePath
    }

    /// 2026-09-30 12:00 in Berlin.
    static let now = FlexibleDate.parse("2026-09-30T12:00:00+02:00")!.date
    static let berlin = TimeZone(identifier: "Europe/Berlin")!

    /// A context whose home folder and debug scope are `root` (the fixtures by
    /// default): paths display as "~/…", nothing outside `root` is allowed.
    static func context(root: String = root, spotlight: any SpotlightQuerying = MockSpotlight(),
                        workspace: MockWorkspace = MockWorkspace(), now: @escaping @Sendable () -> Date = { now },
                        timeZone: TimeZone = berlin, spotlightTimeout: Duration = .seconds(10),
                        folderNames: FolderNames? = nil) -> FileToolContext {
        let canonical = FilePath.canonical(root)
        return FileToolContext(
            spotlight: spotlight, workspace: workspace,
            scope: FileSearchScope.restricted(to: canonical, homeDirectory: canonical),
            policy: FileAccessPolicy(homeDirectory: canonical, orbitDataDirectory: canonical + "/Library/Application Support/Orbit",
                                     restriction: canonical),
            now: now, timeZone: timeZone, spotlightTimeout: spotlightTimeout, folderNames: folderNames
        )
    }
}

/// Live Spotlight on the fixtures (ORBIT_SPOTLIGHT_TESTS=1). Queries are always
/// scoped to the fixture folder, never the home folder or the whole Mac. The
/// folder must be indexed by Spotlight: the repository is, a copy under /tmp is not.
enum SpotlightFixtures {
    static let isEnabled = ProcessInfo.processInfo.environment["ORBIT_SPOTLIGHT_TESTS"] == "1"

    /// Runs prepare-dates.sh once per test run and waits until the index shows its dates.
    static func prepare() async throws {
        try await preparation.value
    }

    private static let preparation = Task {
        try await runPrepareDates()
        let ready = await waitUntil(timeout: .seconds(90)) {
            let lastMonthPDFs = try await names(SpotlightQuery(contentTypes: ["com.adobe.pdf"], modified: lastMonthBounds,
                                                               scopes: [url("Rechnungen")]))
            let usedRecently = try await names(SpotlightQuery(lastUsed: .init(from: Date().addingTimeInterval(-3 * 86_400)),
                                                              scopes: [url("Dokumente")]))
            let changedRecently = try await names(SpotlightQuery(modified: .init(from: Date().addingTimeInterval(-7 * 86_400)),
                                                                 scopes: [url("Dokumente")]))
            return lastMonthPDFs == ["Kontoauszug-2026-08.pdf", "Rechnung-Telekom-2026-08.pdf", "Vodafone-Invoice-2026-08.pdf"]
                && usedRecently == ["Angebot.docx"] && changedRecently == ["Notizen.md", "Protokoll.odt"]
        }
        guard ready else { throw SetupError.notIndexed }
    }

    enum SetupError: Error {
        case prepareDatesFailed(Int32)
        case notIndexed
    }

    static func url(_ relativePath: String) -> URL {
        URL(fileURLWithPath: FileFixtures.path(relativePath), isDirectory: true)
    }

    /// Sorted file names of a query's results.
    static func names(_ query: SpotlightQuery) async throws -> [String] {
        try await LiveSpotlight().search(query, timeout: .seconds(10)).items.map(\.fileSystemName).sorted()
    }

    /// Last month in the Mac's time zone (prepare-dates.sh uses local time).
    static var lastMonthBounds: SpotlightQuery.DateBounds {
        let calendar = Calendar.current
        let thisMonth = calendar.date(from: calendar.dateComponents([.year, .month], from: Date()))!
        let lastMonth = calendar.date(byAdding: .month, value: -1, to: thisMonth)!
        return SpotlightQuery.DateBounds(from: lastMonth, through: thisMonth.addingTimeInterval(-0.001))
    }

    /// "2026-08-01" and "2026-08-31" for last month.
    static var lastMonthArguments: (after: String, before: String) {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyy-MM-dd"
        let bounds = lastMonthBounds
        return (formatter.string(from: bounds.from!), formatter.string(from: bounds.through!))
    }

    static func waitUntil(timeout: Duration, _ condition: () async throws -> Bool) async -> Bool {
        let deadline = ContinuousClock.now + timeout
        while ContinuousClock.now < deadline {
            if (try? await condition()) == true { return true }
            try? await Task.sleep(for: .milliseconds(500))
        }
        return false
    }

    private static func runPrepareDates() async throws {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/bash")
        process.arguments = [FileFixtures.path("prepare-dates.sh")]
        process.standardOutput = FileHandle.nullDevice
        process.standardError = FileHandle.nullDevice
        let status: Int32 = try await withCheckedThrowingContinuation { continuation in
            process.terminationHandler = { continuation.resume(returning: $0.terminationStatus) }
            do {
                try process.run()
            } catch {
                process.terminationHandler = nil
                continuation.resume(throwing: error)
            }
        }
        guard status == 0 else { throw SetupError.prepareDatesFailed(status) }
    }
}
